# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontpage2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pytz
from datetime import datetime
from PyQt5.QtWidgets import QMessageBox
import logo_rc
import settings_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 704)
        MainWindow.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 0, 191, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/1/Logo WGW-Photoroom.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 590, 241, 61))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Arial\";\n"
"")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculer_plage_horaire)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 290, 181, 31))
        self.label_2.setStyleSheet("color: rgb(255, 111, 97);\n"
"font: 75 italic 30pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(156, 156, 156);")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/1/png-clipart-blue-and-green-logo-computer-icons-history-iconfinder-clock-event-history-schedule-time-icon-miscellaneous-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 290, 181, 31))
        self.label_5.setStyleSheet("color: rgb(255, 111, 97);\n"
"font: 75 italic 30pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 330, 111, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 330, 202, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_4.addWidget(self.comboBox_3)
        self.timeEdit_8 = QtWidgets.QTimeEdit(self.verticalLayoutWidget_2)
        self.timeEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit_8.setObjectName("timeEdit_8")
        self.verticalLayout_4.addWidget(self.timeEdit_8)
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.verticalLayoutWidget_2)
        self.timeEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.verticalLayout_4.addWidget(self.timeEdit_7)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1051, -86, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(670, 330, 202, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox_4.setAutoFillBackground(False)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_6.addWidget(self.comboBox_4)
        self.timeEdit_9 = QtWidgets.QTimeEdit(self.verticalLayoutWidget_4)
        self.timeEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit_9.setObjectName("timeEdit_9")
        self.verticalLayout_6.addWidget(self.timeEdit_9)
        self.timeEdit_10 = QtWidgets.QTimeEdit(self.verticalLayoutWidget_4)
        self.timeEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeEdit_10.setObjectName("timeEdit_10")
        self.verticalLayout_6.addWidget(self.timeEdit_10)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(560, 330, 111, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_19.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_20.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_21.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHistorique = QtWidgets.QAction(MainWindow)
        self.actionHistorique.setObjectName("actionHistorique")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        timezones = sorted(pytz.all_timezones)
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Calculer la plage horaire"))
        self.label_2.setText(_translate("MainWindow", "PAYS N°1"))
        self.label_5.setText(_translate("MainWindow", "PAYS N°2"))
        self.label_15.setText(_translate("MainWindow", "Pays :"))
        self.label_17.setText(_translate("MainWindow", "Heure de début :"))
        self.label_18.setText(_translate("MainWindow", "Heure de fin :"))
        self.comboBox_3.addItems(timezones)
        self.comboBox_4.addItems(timezones)
        self.label_19.setText(_translate("MainWindow", "Pays :"))
        self.label_20.setText(_translate("MainWindow", "Heure de début :"))
        self.label_21.setText(_translate("MainWindow", "Heure de fin :"))
        self.actionHistorique.setText(_translate("MainWindow", "Historique"))


  

    def calculer_plage_horaire(self):
        # Récupération des valeurs
        pays1 = self.comboBox_3.currentText()
        pays2 = self.comboBox_4.currentText()
        heure_debut1 = self.timeEdit_8.time()
        heure_fin1 = self.timeEdit_7.time()
        heure_debut2 = self.timeEdit_9.time()
        heure_fin2 = self.timeEdit_10.time()

        # Conversion en datetime + fuseaux horaires
        tz1 = pytz.timezone(pays1)
        tz2 = pytz.timezone(pays2)

        # Date arbitraire pour la conversion
        date_ref = datetime(2025, 1, 1)

        debut1 = tz1.localize(datetime(date_ref.year, date_ref.month, date_ref.day, heure_debut1.hour(), heure_debut1.minute()))
        fin1 = tz1.localize(datetime(date_ref.year, date_ref.month, date_ref.day, heure_fin1.hour(), heure_fin1.minute()))

        debut2 = tz2.localize(datetime(date_ref.year, date_ref.month, date_ref.day, heure_debut2.hour(), heure_debut2.minute()))
        fin2 = tz2.localize(datetime(date_ref.year, date_ref.month, date_ref.day, heure_fin2.hour(), heure_fin2.minute()))

        # Conversion des plages horaires en UTC
        debut1_utc = debut1.astimezone(pytz.utc)
        fin1_utc = fin1.astimezone(pytz.utc)
        debut2_utc = debut2.astimezone(pytz.utc)
        fin2_utc = fin2.astimezone(pytz.utc)

        # Intersection des plages horaires en UTC
        debut_commum = max(debut1_utc, debut2_utc)
        fin_commune = min(fin1_utc, fin2_utc)

        # Vérification s'il y a un créneau valide
        if debut_commum < fin_commune:
                # Conversion en heure locale pour les deux pays
                debut_final1 = debut_commum.astimezone(tz1).strftime("%H:%M")
                fin_final1 = fin_commune.astimezone(tz1).strftime("%H:%M")

                debut_final2 = debut_commum.astimezone(tz2).strftime("%H:%M")
                fin_final2 = fin_commune.astimezone(tz2).strftime("%H:%M")

                message = (f"Plage horaire commune :\n\n"
                        f"📍 {pays1} : {debut_final1} - {fin_final1}\n"
                        f"📍 {pays2} : {debut_final2} - {fin_final2}")
        else:
                message = "❌ Aucune plage horaire compatible trouvée."

        # Affichage du résultat
        QMessageBox.information(None, "Résultat", message)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
